import { useState, useEffect, useMemo, useRef } from "react";
import type { WorkspacePayload } from "./types.ts";
import { ELEMENT_CHAPTER } from "@biz42/core";
import type { Element, Edge, DocumentAst, Diagram, BlockType } from "@biz42/core";
import { DocumentView } from "./DocumentView.tsx";
import { Sidebar } from "./Sidebar.tsx";
import { useTheme } from "./useTheme.ts";
import styles from "./App.module.css";
import "./styles.css";

// ---------------------------------------------------------------------------
// Load workspace
// ---------------------------------------------------------------------------

async function fetchWorkspace(): Promise<WorkspacePayload> {
  if (window.__WORKSPACE__) return window.__WORKSPACE__;
  const res = await fetch("/api/workspace");
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json() as Promise<WorkspacePayload>;
}

// ---------------------------------------------------------------------------
// Hash routing
//
// URL scheme (mirrors arc42-language):
//   /#02-signals.biz42.md             → navigate to doc
//   /#02-signals.biz42.md:el-some-id  → navigate to doc + auto-expand element card
//
// Diagram clickable nodes still use  #chapter-{n}-{id}  (generated by DiagramView).
// We translate that on hashchange to the /#filename:el-{id} form.
// ---------------------------------------------------------------------------

function basename(filePath: string): string {
  return filePath.split("/").pop() ?? filePath;
}

function parseHash(hash: string): { docFile: string; elementId: string | null } {
  if (!hash || hash === "#") return { docFile: "", elementId: null };
  const fragment = hash.slice(1); // strip leading #
  const colonIdx = fragment.indexOf(":");
  if (colonIdx === -1) return { docFile: fragment, elementId: null };
  const after = fragment.slice(colonIdx + 1);
  const elementId = after.startsWith("el-") ? after.slice(3) : null;
  return { docFile: fragment.slice(0, colonIdx), elementId };
}

function hashForDoc(filePath: string, elementId?: string): string {
  const base = "#" + basename(filePath);
  return elementId ? `${base}:el-${elementId}` : base;
}

function docIndexFromHash(documents: DocumentAst[], hash: string): number {
  const { docFile } = parseHash(hash);
  if (!docFile) return 0;

  // Exact filename match first
  const exact = documents.findIndex((d) => basename(d.filePath) === docFile);
  if (exact >= 0) return exact;

  // chapter-{n}-{id} form: map chapter number to document
  const chapterMatch = /^chapter-(\d+)-/.exec(docFile);
  if (chapterMatch) {
    const ch = parseInt(chapterMatch[1]!, 10);
    const byChapter = documents.findIndex((doc) => {
      const m = /^(\d+)-/.exec(basename(doc.filePath));
      return m ? parseInt(m[1]!, 10) === ch : false;
    });
    if (byChapter >= 0) return byChapter;
  }

  return 0;
}

function useHashRouter(documents: DocumentAst[]) {
  const [activeDocIndex, setActiveDocIndex] = useState(() =>
    docIndexFromHash(documents, window.location.hash),
  );
  const [targetElementId, setTargetElementId] = useState<string | null>(() => {
    const { elementId } = parseHash(window.location.hash);
    return elementId;
  });

  // Re-resolve the initial hash once documents are available.
  // On first render documents may be empty (workspace not yet loaded), so
  // docIndexFromHash returns 0. As soon as documents first populate, re-evaluate
  // the current hash so a direct URL like /#13-cashflow.biz42.md lands on
  // the right document rather than defaulting to document 0.
  // The flag ensures SSE live-reload updates never override a user's manual navigation.
  const initialHashResolved = useRef(false);
  useEffect(() => {
    if (documents.length === 0) return;
    if (initialHashResolved.current) return;
    initialHashResolved.current = true;
    const hash = window.location.hash;
    const { docFile } = parseHash(hash);
    if (!docFile) return;
    const idx = documents.findIndex((d) => basename(d.filePath) === docFile);
    if (idx >= 0) {
      setActiveDocIndex(idx);
    }
  }, [documents]);

  useEffect(() => {
    function onHashChange() {
      const hash = window.location.hash;

      // Translate #chapter-{n}-{id} (from diagram node clicks) to #filename:el-{id}
      const chapterMatch = /^#chapter-(\d+)-(.+)$/.exec(hash);
      if (chapterMatch) {
        const ch = parseInt(chapterMatch[1]!, 10);
        const elementId = chapterMatch[2]!;
        const doc = documents.find((d) => {
          const m = /^(\d+)-/.exec(basename(d.filePath));
          return m ? parseInt(m[1]!, 10) === ch : false;
        });
        if (doc) {
          // Replace hash with canonical form and let the event re-fire
          window.location.hash = hashForDoc(doc.filePath, elementId).slice(1);
          return;
        }
      }

      const { docFile, elementId } = parseHash(hash);
      const newIdx = docFile ? documents.findIndex((d) => basename(d.filePath) === docFile) : 0;
      setActiveDocIndex(newIdx >= 0 ? newIdx : 0);
      setTargetElementId(elementId);
    }

    window.addEventListener("hashchange", onHashChange);
    return () => window.removeEventListener("hashchange", onHashChange);
  }, [documents]);

  function navigateToDoc(index: number) {
    const doc = documents[index];
    if (!doc) return;
    const newHash = hashForDoc(doc.filePath);
    // Always push the hash so refresh restores the doc
    window.location.hash = newHash.slice(1);
  }

  return {
    activeDocIndex,
    targetElementId,
    clearTargetElementId: () => setTargetElementId(null),
    navigateToDoc,
  };
}

// ---------------------------------------------------------------------------
// Main App
// ---------------------------------------------------------------------------

export function App() {
  const [payload, setPayload] = useState<WorkspacePayload | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [agentView, setAgentView] = useState(false);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const { theme, toggle: toggleTheme } = useTheme();

  useEffect(() => {
    fetchWorkspace()
      .then((p) => {
        setPayload(p);
        // Only set default hash if there's no existing hash
        if (p.documents.length > 0 && !window.location.hash) {
          const first = p.documents[0]!;
          window.location.hash = basename(first.filePath);
        }
      })
      .catch((e: unknown) => setError(String(e)));

    // SSE live reload
    const es = new EventSource("/api/workspace/events");
    es.addEventListener("workspace", () => {
      fetchWorkspace()
        .then(setPayload)
        .catch(() => null);
    });
    return () => es.close();
  }, []);

  const documents: DocumentAst[] = payload?.documents ?? [];
  const { activeDocIndex, targetElementId, clearTargetElementId, navigateToDoc } =
    useHashRouter(documents);

  // Build elements map (id → element) — used by ElementCard and AstNodeRenderer
  const elementsMap = useMemo(() => {
    const map = new Map<string, Element>();
    for (const el of payload?.elements ?? []) map.set(el.id, el);
    return map;
  }, [payload?.elements]);

  // Build elementDocMap (elementId → filePath basename) — for cross-doc ref links
  const elementDocMap = useMemo(() => {
    const map = new Map<string, string>();
    for (const doc of payload?.documents ?? []) {
      for (const node of doc.nodes) {
        if (node.kind === "block") {
          const id = (node as { attributes: Record<string, string> }).attributes["id"];
          if (id) map.set(id, doc.filePath);
        }
      }
    }
    return map;
  }, [payload?.documents]);

  // Build chapterMap (elementId → chapter number) for DiagramView
  const chapterMap = useMemo(() => {
    const map = new Map<string, number>();
    for (const el of payload?.elements ?? []) {
      map.set(el.id, ELEMENT_CHAPTER[el.kind as BlockType]);
    }
    return map;
  }, [payload?.elements]);

  const edges: Edge[] = payload?.edges ?? [];
  const diagrams: Diagram[] = payload?.diagrams ?? [];

  if (error) {
    return (
      <div className={styles.loadError}>
        <h1>Failed to load workspace</h1>
        <pre>{error}</pre>
      </div>
    );
  }

  if (!payload) {
    return (
      <div className={styles.loadSpinner}>
        <div className={styles.spinner} aria-hidden="true" />
        <span>Loading…</span>
      </div>
    );
  }

  const activeDoc = activeDocIndex !== null ? (documents[activeDocIndex] ?? null) : null;

  return (
    <div className={styles.layout}>
      <button
        className={styles.menuButton}
        type="button"
        aria-label="Open document navigation"
        aria-expanded={sidebarOpen}
        onClick={() => setSidebarOpen(true)}
      >
        <span aria-hidden="true">☰</span>
        <span>Contents</span>
      </button>
      {sidebarOpen && (
        <button
          className={styles.sidebarBackdrop}
          type="button"
          aria-label="Close document navigation"
          onClick={() => setSidebarOpen(false)}
        />
      )}
      <Sidebar
        documents={documents}
        activeDocIndex={activeDocIndex}
        onSelectDoc={(idx) => {
          navigateToDoc(idx);
          setSidebarOpen(false);
        }}
        viewMode={agentView ? "agent" : "human"}
        onToggleViewMode={() => setAgentView((v) => !v)}
        theme={theme}
        onToggleTheme={toggleTheme}
        open={sidebarOpen}
        onClose={() => setSidebarOpen(false)}
      />

      <main className={styles.main}>
        {activeDoc ? (
          <DocumentView
            doc={activeDoc}
            viewMode={agentView ? "agent" : "human"}
            elementsMap={elementsMap}
            elementDocMap={elementDocMap}
            edges={edges}
            diagrams={diagrams}
            chapterMap={chapterMap}
            targetElementId={targetElementId}
            onTargetConsumed={clearTargetElementId}
          />
        ) : (
          <div style={{ color: "var(--text-muted)", padding: "2rem" }}>No document selected.</div>
        )}
      </main>
    </div>
  );
}
