import { useState, useEffect, useMemo, useRef } from "react";
import type { WorkspacePayload } from "./types.ts";
import { ELEMENT_CHAPTER } from "@biz42/core";
import type { Element, Edge, DocumentAst, Diagram, BlockType } from "@biz42/core";
import { DocumentView } from "./DocumentView.tsx";
import "./styles.css";

// ---------------------------------------------------------------------------
// Load workspace
// ---------------------------------------------------------------------------

async function fetchWorkspace(): Promise<WorkspacePayload> {
  if (window.__WORKSPACE__) return window.__WORKSPACE__;
  const res = await fetch("/api/workspace");
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json() as Promise<WorkspacePayload>;
}

// ---------------------------------------------------------------------------
// Hash routing
//
// URL scheme (mirrors arc42-language):
//   /#02-signals.biz42.md             → navigate to doc
//   /#02-signals.biz42.md:el-some-id  → navigate to doc + auto-expand element card
//
// Diagram clickable nodes still use  #chapter-{n}-{id}  (generated by DiagramView).
// We translate that on hashchange to the /#filename:el-{id} form.
// ---------------------------------------------------------------------------

function basename(filePath: string): string {
  return filePath.split("/").pop() ?? filePath;
}

function parseHash(hash: string): { docFile: string; elementId: string | null } {
  if (!hash || hash === "#") return { docFile: "", elementId: null };
  const fragment = hash.slice(1); // strip leading #
  const colonIdx = fragment.indexOf(":");
  if (colonIdx === -1) return { docFile: fragment, elementId: null };
  const after = fragment.slice(colonIdx + 1);
  const elementId = after.startsWith("el-") ? after.slice(3) : null;
  return { docFile: fragment.slice(0, colonIdx), elementId };
}

function hashForDoc(filePath: string, elementId?: string): string {
  const base = "#" + basename(filePath);
  return elementId ? `${base}:el-${elementId}` : base;
}

function docIndexFromHash(documents: DocumentAst[], hash: string): number {
  const { docFile } = parseHash(hash);
  if (!docFile) return 0;

  // Exact filename match first
  const exact = documents.findIndex((d) => basename(d.filePath) === docFile);
  if (exact >= 0) return exact;

  // chapter-{n}-{id} form: map chapter number to document
  const chapterMatch = /^chapter-(\d+)-/.exec(docFile);
  if (chapterMatch) {
    const ch = parseInt(chapterMatch[1]!, 10);
    const byChapter = documents.findIndex((doc) => {
      const m = /^(\d+)-/.exec(basename(doc.filePath));
      return m ? parseInt(m[1]!, 10) === ch : false;
    });
    if (byChapter >= 0) return byChapter;
  }

  return 0;
}

function useHashRouter(documents: DocumentAst[]) {
  const [activeDocIndex, setActiveDocIndex] = useState(() =>
    docIndexFromHash(documents, window.location.hash),
  );
  const [targetElementId, setTargetElementId] = useState<string | null>(() => {
    const { elementId } = parseHash(window.location.hash);
    return elementId;
  });

  // Re-resolve the initial hash once documents are available.
  // On first render documents may be empty (workspace not yet loaded), so
  // docIndexFromHash returns 0. As soon as documents first populate, re-evaluate
  // the current hash so a direct URL like /#13-cashflow.biz42.md lands on
  // the right document rather than defaulting to document 0.
  // The flag ensures SSE live-reload updates never override a user's manual navigation.
  const initialHashResolved = useRef(false);
  useEffect(() => {
    if (documents.length === 0) return;
    if (initialHashResolved.current) return;
    initialHashResolved.current = true;
    const hash = window.location.hash;
    const { docFile } = parseHash(hash);
    if (!docFile) return;
    const idx = documents.findIndex((d) => basename(d.filePath) === docFile);
    if (idx >= 0) {
      setActiveDocIndex(idx);
    }
  }, [documents]);

  useEffect(() => {
    function onHashChange() {
      const hash = window.location.hash;

      // Translate #chapter-{n}-{id} (from diagram node clicks) to #filename:el-{id}
      const chapterMatch = /^#chapter-(\d+)-(.+)$/.exec(hash);
      if (chapterMatch) {
        const ch = parseInt(chapterMatch[1]!, 10);
        const elementId = chapterMatch[2]!;
        const doc = documents.find((d) => {
          const m = /^(\d+)-/.exec(basename(d.filePath));
          return m ? parseInt(m[1]!, 10) === ch : false;
        });
        if (doc) {
          // Replace hash with canonical form and let the event re-fire
          window.location.hash = hashForDoc(doc.filePath, elementId).slice(1);
          return;
        }
      }

      const { docFile, elementId } = parseHash(hash);
      const newIdx = docFile ? documents.findIndex((d) => basename(d.filePath) === docFile) : 0;
      setActiveDocIndex(newIdx >= 0 ? newIdx : 0);
      setTargetElementId(elementId);
    }

    window.addEventListener("hashchange", onHashChange);
    return () => window.removeEventListener("hashchange", onHashChange);
  }, [documents]);

  function navigateToDoc(index: number) {
    const doc = documents[index];
    if (!doc) return;
    const newHash = hashForDoc(doc.filePath);
    // Always push the hash so refresh restores the doc
    window.location.hash = newHash.slice(1);
  }

  return {
    activeDocIndex,
    targetElementId,
    clearTargetElementId: () => setTargetElementId(null),
    navigateToDoc,
  };
}

// ---------------------------------------------------------------------------
// Sidebar
// ---------------------------------------------------------------------------

function docTitle(doc: DocumentAst): string {
  const h1 = doc.nodes.find((n) => n.kind === "heading" && (n as { level: number }).level === 1);
  if (h1) return (h1 as { text: string }).text;
  const base = basename(doc.filePath);
  return base.replace(/\.biz42\.md$/, "");
}

function Sidebar({
  documents,
  activeDocIndex,
  onSelectDoc,
}: {
  documents: DocumentAst[];
  activeDocIndex: number | null;
  onSelectDoc: (idx: number) => void;
}) {
  return (
    <nav
      style={{
        width: 240,
        flexShrink: 0,
        borderRight: "1px solid var(--border)",
        padding: "16px 0",
        overflowY: "auto",
        background: "var(--bg-sidebar)",
      }}
    >
      <div
        style={{
          padding: "0 16px 12px",
          fontWeight: 700,
          fontSize: 13,
          color: "var(--text-muted)",
          letterSpacing: "0.05em",
          textTransform: "uppercase",
        }}
      >
        biz42
      </div>
      {documents.map((doc, idx) => {
        const active = activeDocIndex === idx;
        const base = basename(doc.filePath);
        const numMatch = /^(\d+)-/.exec(base);
        const num = numMatch ? numMatch[1] : null;
        const title = docTitle(doc);
        return (
          <button
            key={doc.filePath}
            onClick={() => onSelectDoc(idx)}
            style={{
              display: "flex",
              alignItems: "baseline",
              gap: 8,
              width: "100%",
              textAlign: "left",
              padding: "6px 16px",
              background: active
                ? "color-mix(in srgb, var(--accent) 10%, transparent)"
                : "transparent",
              border: "none",
              borderLeft: active ? "3px solid var(--accent)" : "3px solid transparent",
              cursor: "pointer",
              fontSize: 13,
              fontWeight: active ? 600 : 400,
              color: active ? "var(--accent)" : "var(--text)",
            }}
          >
            {num && (
              <span style={{ fontSize: 11, color: "var(--text-muted)", minWidth: 18 }}>{num}</span>
            )}
            <span>{title}</span>
          </button>
        );
      })}
    </nav>
  );
}

// ---------------------------------------------------------------------------
// Main App
// ---------------------------------------------------------------------------

export function App() {
  const [payload, setPayload] = useState<WorkspacePayload | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [agentView, setAgentView] = useState(false);

  useEffect(() => {
    fetchWorkspace()
      .then((p) => {
        setPayload(p);
        // Only set default hash if there's no existing hash
        if (p.documents.length > 0 && !window.location.hash) {
          const first = p.documents[0]!;
          window.location.hash = basename(first.filePath);
        }
      })
      .catch((e: unknown) => setError(String(e)));

    // SSE live reload
    const es = new EventSource("/api/workspace/events");
    es.addEventListener("workspace", () => {
      fetchWorkspace()
        .then(setPayload)
        .catch(() => null);
    });
    return () => es.close();
  }, []);

  const documents: DocumentAst[] = payload?.documents ?? [];
  const { activeDocIndex, targetElementId, clearTargetElementId, navigateToDoc } =
    useHashRouter(documents);

  // Build elements map (id → element) — used by ElementCard and AstNodeRenderer
  const elementsMap = useMemo(() => {
    const map = new Map<string, Element>();
    for (const el of payload?.elements ?? []) map.set(el.id, el);
    return map;
  }, [payload?.elements]);

  // Build elementDocMap (elementId → filePath basename) — for cross-doc ref links
  const elementDocMap = useMemo(() => {
    const map = new Map<string, string>();
    for (const doc of payload?.documents ?? []) {
      for (const node of doc.nodes) {
        if (node.kind === "block") {
          const id = (node as { attributes: Record<string, string> }).attributes["id"];
          if (id) map.set(id, doc.filePath);
        }
      }
    }
    return map;
  }, [payload?.documents]);

  // Build chapterMap (elementId → chapter number) for DiagramView
  const chapterMap = useMemo(() => {
    const map = new Map<string, number>();
    for (const el of payload?.elements ?? []) {
      map.set(el.id, ELEMENT_CHAPTER[el.kind as BlockType]);
    }
    return map;
  }, [payload?.elements]);

  const edges: Edge[] = payload?.edges ?? [];
  const diagrams: Diagram[] = payload?.diagrams ?? [];

  if (error) {
    return (
      <div style={{ padding: 32, color: "var(--color-error)" }}>
        <strong>Failed to load workspace:</strong> {error}
      </div>
    );
  }

  if (!payload) {
    return <div style={{ padding: 32, color: "var(--text-muted)" }}>Loading…</div>;
  }

  const activeDoc = activeDocIndex !== null ? (documents[activeDocIndex] ?? null) : null;

  return (
    <div style={{ display: "flex", height: "100vh", overflow: "hidden" }}>
      <Sidebar documents={documents} activeDocIndex={activeDocIndex} onSelectDoc={navigateToDoc} />

      <main style={{ flex: 1, overflowY: "auto", padding: "20px 36px" }}>
        {/* View mode toggle */}
        <div
          style={{
            display: "flex",
            justifyContent: "flex-end",
            alignItems: "center",
            marginBottom: 8,
          }}
        >
          <div style={{ display: "flex", gap: 8 }}>
            <button
              onClick={() => setAgentView(false)}
              style={{
                padding: "4px 12px",
                borderRadius: 4,
                border: "1px solid var(--border)",
                background: !agentView ? "var(--accent)" : "transparent",
                color: !agentView ? "#fff" : "var(--text)",
                cursor: "pointer",
                fontSize: 12,
              }}
            >
              Human
            </button>
            <button
              onClick={() => setAgentView(true)}
              style={{
                padding: "4px 12px",
                borderRadius: 4,
                border: "1px solid var(--border)",
                background: agentView ? "var(--accent)" : "transparent",
                color: agentView ? "#fff" : "var(--text)",
                cursor: "pointer",
                fontSize: 12,
              }}
            >
              Agent
            </button>
          </div>
        </div>

        {/* Document content */}
        {activeDoc ? (
          <DocumentView
            doc={activeDoc}
            viewMode={agentView ? "agent" : "human"}
            elementsMap={elementsMap}
            elementDocMap={elementDocMap}
            edges={edges}
            diagrams={diagrams}
            chapterMap={chapterMap}
            targetElementId={targetElementId}
            onTargetConsumed={clearTargetElementId}
          />
        ) : (
          <div style={{ color: "var(--text-muted)", padding: "2rem" }}>No document selected.</div>
        )}
      </main>
    </div>
  );
}
